# Generated by Django 5.0.6 on 2024-05-24 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, verbose_name='User First Name')),
                ('last_name', models.CharField(max_length=128, verbose_name='User Last Name')),
                ('gender', models.CharField(choices=[('NA', 'NA'), ('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='NA', max_length=128, verbose_name='Gender')),
                ('u_name', models.CharField(max_length=200, verbose_name='User Name')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('role', models.CharField(choices=[('NA', 'NA'), ('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Other', 'Other')], default='NA', max_length=128, verbose_name='Role')),
                ('contact', models.CharField(max_length=128, verbose_name='User Contact')),
                ('address', models.CharField(max_length=1024, verbose_name='User Address')),
                ('email_address', models.CharField(max_length=128, verbose_name='User email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Clinic Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Clinic updated')),
                ('cid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_users', to='clinic.clinic')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
