# Generated by Django 5.0.6 on 2024-06-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], max_length=16, verbose_name='Role'),
        ),
    ]
