# Generated by Django 5.0.6 on 2024-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='aadhar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aadhar'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Patient Created'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pan'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Patient updated'),
        ),
    ]
