# Generated by Django 5.0.6 on 2024-06-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_patient_aadhar_alter_patient_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency_Contact'),
        ),
    ]
