# Generated by Django 5.0.6 on 2024-06-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('NA', 'Na'), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=16, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile'),
        ),
    ]
