# Generated by Django 5.0.6 on 2024-07-03 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_user_gender_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_day', models.CharField(blank=True, choices=[('Monday', 'MONDAY'), ('Tuesday', 'TUESDAY'), ('Wednesday', 'WEDNESDAY'), ('Thursday', 'THURSDAY'), ('Friday', 'FRIDAY'), ('Saturday', 'SATURDAY'), ('Sunday', 'SUNDAY')], max_length=100, null=True, verbose_name='Slot Day')),
                ('slot_time', models.TimeField(blank=True, max_length=100, null=True, verbose_name='Slot Time')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Slot Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Slot History Updated')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor')),
            ],
            options={
                'verbose_name': 'Slot',
                'verbose_name_plural': 'Slots',
            },
        ),
        migrations.CreateModel(
            name='SlotCalendar',
            fields=[
                ('scid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField(verbose_name='Slot Date')),
                ('slot_status', models.CharField(blank=True, choices=[('Open', 'OPEN'), ('Booked', 'BOOKED'), ('Reserved', 'RESERVED')], max_length=100, null=True, verbose_name='Slot Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Slot Calendar Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Slot Calendar Updated')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.slot')),
            ],
            options={
                'verbose_name': 'Slot Calendar',
                'verbose_name_plural': 'Slot Calendars',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Appointment Created')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Appointment Updated')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
                ('scid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointment.slotcalendar')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
